<a href="https://colab.research.google.com/github/sophicist/Aesops/blob/master/TextAnalytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import pandas as pd
import nltk

In [21]:
text = pd.DataFrame(columns = ["text","Sentiment"])
text["text"] = [
                "He is the nicing  guy",
                "john went to the market",
                "you are an idiot",
                "He is a male stripper",
                "she did not like him very much",
                "I have gotten a job",
                "there was war after elections",
                "Marving sleeps until late in the morning",
                "you have ugly legs",
                "The president is now fat"
                ]
text["Sentiment"] = ["Positive","Neutral","Negative","Negative","Negative","Positive","Negative","Neutral","Negative","Negative"]
text.head()

                             text Sentiment
0           He is the nicing  guy  Positive
1         john went to the market   Neutral
2                you are an idiot  Negative
3           He is a male stripper  Negative
4  she did not like him very much  Negative

In [25]:
# word tokenization
from string import punctuation
# nltk.download('punkt')
nltk.download('stopwords')
stop = nltk.corpus.stopwords.words("english")+list(punctuation)
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer 





def cleaner(sentence):
  # tokenize
  clean = nltk.word_tokenize(sentence)
  # remove stopwords
  clean = [i for i in clean if not i in stop]
  # lematize
  lemmatizer = WordNetLemmatizer()
  clean = [lemmatizer.lemmatize(i) for i in clean]

  return " ".join(clean)

cleaner(text["text"][0])
# remove stopwords
# stemming
# lematization
# n-grams analysis
# visualization

text["text"] = list(map(cleaner,text["text"]))
text.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

               text Sentiment
0     He nicing guy  Positive
1  john went market   Neutral
2             idiot  Negative
3  He male stripper  Negative
4         like much  Negative

In [26]:
# visualize the data
## use a frequency chart
## word cloud

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

x = text["text"]
y = text["Sentiment"]

# vectorize the data (learn more about vectorization and bag of words)

vector = CountVectorizer()
X = vector.fit_transform(x)
print(vector.get_feature_names_out())
X.toarray()

dy = pd.DataFrame(X.toarray(),columns = vector.get_feature_names_out())
dy.head()

['election' 'fat' 'gotten' 'guy' 'he' 'idiot' 'job' 'john' 'late' 'leg'
 'like' 'male' 'market' 'marving' 'morning' 'much' 'nicing' 'president'
 'sleep' 'stripper' 'the' 'ugly' 'war' 'went']

,election,fat,gotten,guy,he,idiot,job,john,late,leg,...,morning,much,nicing,president,sleep,stripper,the,ugly,war,went
0,0,0,0,1,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [38]:
x_train, x_test,y_train,y_test = train_test_split(X,y)
model =  MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [39]:
pred = model.predict(x_test)
print(accuracy_score(pred,y_test))

0.3333333333333333